import npyscreen
import curses

class colors(npyscreen.ThemeManager): 
    _colors_to_define = (('WHITE_BLACK',      curses.COLOR_WHITE,      curses.COLOR_BLACK),
                        ('BLACK_WHITE',      curses.COLOR_BLACK,      curses.COLOR_WHITE),
                        ('BLUE_BLACK',       curses.COLOR_BLUE,       curses.COLOR_BLACK),
                        ('CYAN_BLACK',       curses.COLOR_CYAN,       curses.COLOR_BLACK),
                        ('GREEN_BLACK',      curses.COLOR_GREEN,      curses.COLOR_BLACK),
                        ('MAGENTA_BLACK',    curses.COLOR_MAGENTA,    curses.COLOR_BLACK),
                        ('RED_BLACK',        curses.COLOR_RED,        curses.COLOR_BLACK),
                        ('YELLOW_BLACK',     curses.COLOR_YELLOW,     curses.COLOR_BLACK),
                        ('BLUE_GREEN',       curses.COLOR_BLUE,       curses.COLOR_GREEN),
                        ('GREEN_BLUE',       curses.COLOR_GREEN,      curses.COLOR_BLUE),
                        ('WHITE_GREEN',      curses.COLOR_WHITE,      curses.COLOR_GREEN),
                        ('WHITE_BLUE',       curses.COLOR_WHITE,      curses.COLOR_BLUE),
                        ('WHITE_RED', curses.COLOR_WHITE,  curses.COLOR_RED),
                        ('BLACK_RED', curses.COLOR_BLACK,  curses.COLOR_RED),
                        ('BLACK_GREEN',      curses.COLOR_BLACK,curses.COLOR_GREEN),
                        ('BLACK_BLUE',   curses.COLOR_BLACK,      curses.COLOR_BLUE),
                        ('BLACK_YELLOW',curses.COLOR_BLACK, curses.COLOR_YELLOW),
                        ('WHITE_YELLOW', curses.COLOR_WHITE, curses.COLOR_YELLOW),
                        ('BLACK_CYAN', curses.COLOR_BLACK,curses.COLOR_CYAN),
                        ('WHITE_CYAN', curses.COLOR_WHITE,curses.COLOR_CYAN) )

    default_colors = {
        'DEFAULT'     : 'WHITE_BLACK',
        'FORMDEFAULT' : 'WHITE_BLACK',
        'NO_EDIT'     : 'BLUE_BLACK',
        'STANDOUT'    : 'CYAN_BLACK',
        'CURSOR'      : 'WHITE_BLACK',
        'CURSOR_INVERSE': 'BLACK_WHITE',
        'LABEL'       : 'GREEN_BLACK',
        'LABELBOLD'   : 'WHITE_BLACK',
        'CONTROL'     : 'YELLOW_BLACK',
        'IMPORTANT'   : 'GREEN_BLACK',
        'SAFE'        : 'GREEN_BLACK',
        'WARNING'     : 'YELLOW_BLACK',
        'DANGER'      : 'RED_BLACK',
        'CRITICAL'    : 'BLACK_RED',
        'GOOD'        : 'GREEN_BLACK',
        'GOODHL'      : 'GREEN_BLACK',
        'VERYGOOD'    : 'BLACK_GREEN',
        'CAUTION'     : 'YELLOW_BLACK',
        'CAUTIONHL'   : 'BLACK_YELLOW',
        'BGT'         : 'BLUE_GREEN',
        'GBT'         : 'GREEN_BLUE',
        'W_G'         : 'WHITE_GREEN',
        'W_B'         : 'WHITE_BLUE',
        'W_R'         : 'WHITE_RED',
        'W_Y'         : 'WHITE_YELLOW',
        'W_C'         : 'WHITE_CYAN',
        'B_G'         : 'BLACK_GREEN',
        'B_B'         : 'BLACK_BLUE',
        'B_C'         : 'BLACK_CYAN',
        'B_Y'         : 'BLACK_YELLOW',
        'B_R'         : 'BLACK_RED'
    }